- CHANGELOG.md
- lua/rustaceanvim/compat.lua
> fix(compat): add missing nil checks

- lua/rustaceanvim/config/init.lua
- lua/rustaceanvim/config/internal.lua
- lua/rustaceanvim/dap.lua
- lua/rustaceanvim/shell.lua
This:
Sorry for cramming so many little bits and pieces in at once, this is basically just a "fix some of the things that were blockers for me with lldb-vscode". My main use-case was to get Bevy engine debugging working, which this does.
I'm submitting it as a WIP so you can have a quick scan and tell me if you agree with the approach, as I don't write a great deal of Lua and there are probably some wildly non-idiomatic things you can point out! I've tried to follow the overall approach of what was there before though.
I'll look at adding some tests and tidying up tomorrow.
> feat(dap): support dynamically compiled executable

- lua/rustaceanvim/dap.lua
This:
I can't promise this is also true for code-lldb? But it seems likely. Tests are still green.
Fixes #73
> fix(dap): lldb library paths are strings

- CHANGELOG.md
- README.md
- lua/rustaceanvim/config/internal.lua
> feat(dap): auto-detect `codelldb` if installed using mason.nvim

- lua/rustaceanvim/config/internal.lua
This:
`has_package` is true if the package is in the Mason registry, which is not quite what we want here. This fixes an error in the case where Mason is installed, but `codelldb` is not.
Fixes #96
> fix(dap): has_package -> is_installed

- CHANGELOG.md
- lua/rustaceanvim/commands/crate_graph.lua
- lua/rustaceanvim/dap.lua
> fix(dap): only add sourceMap and lldb commands if the files exist

- CHANGELOG.md
- README.md
- lua/rustaceanvim/commands/hir.lua
- lua/rustaceanvim/commands/init.lua
> feat: `viewHir` command

- CHANGELOG.md
- lua/rustaceanvim/commands/explain_error.lua
- lua/rustaceanvim/config/check.lua
- lua/rustaceanvim/config/init.lua
- lua/rustaceanvim/config/internal.lua
- lua/rustaceanvim/hover_actions.lua
- lua/rustaceanvim/lsp.lua
By utilizing the existing optionscan avoid user modifying their config.I think it would be better to do it this way.
> feat(config): apply float_win_config to floating windows

- CHANGELOG.md
- lua/rustaceanvim/config/init.lua
- lua/rustaceanvim/config/internal.lua
- lua/rustaceanvim/dap.lua
Fixes #139.
@SlayerOfTheBad if I understand your description correctly, this should fix it?
I haven't had time to test it yet...
> fix(dap): don't load `lldb_commands` when using `codelldb`

- ftplugin/rust.lua
fixes #179 by sanitizing the actual command from hover actions debug. 
I have tested this manually on my local machine. The final command when from `run` to `build` after sanitization and dap was run.
> fix(ftplugin): Properly sanitize hover actions debug command

- CHANGELOG.md
- lua/rustaceanvim/commands/code_action_group.lua
> fix(lsp): focus lost after `:RustLsp codeAction` second float opens

- CHANGELOG.md
- README.md
- doc/rustaceanvim.txt
- lua/rustaceanvim/commands/code_action_group.lua
- lua/rustaceanvim/config/init.lua
- lua/rustaceanvim/config/internal.lua
> feat(lsp): option to fall back to `vim.ui.select` for code action

- CHANGELOG.md
- README.md
- lua/rustaceanvim/commands/init.lua
- lua/rustaceanvim/commands/rustc_unpretty.lua
- lua/rustaceanvim/config/check.lua
- lua/rustaceanvim/config/init.lua
- lua/rustaceanvim/config/internal.lua
Use `rustc -Z unpretty=mir` to inspect mir and other things,
and achieve an experience similar to Rust Playground.
The rust-analyzer view does not support viewing MIR for async blocks,
but rustc can do it.
> feat(rustc_unpretty): use rustc inspect mir

- CHANGELOG.md
- README.md
- doc/rustaceanvim.txt
- ftplugin/rust.lua
- lua/rustaceanvim/commands/init.lua
- lua/rustaceanvim/commands/rustc_unpretty.lua
- lua/rustaceanvim/config/check.lua
- lua/rustaceanvim/config/init.lua
- lua/rustaceanvim/config/internal.lua
- lua/rustaceanvim/health.lua
- lua/rustaceanvim/init.lua
> feat(commands): `Rustc unpretty args[]`

- CHANGELOG.md
- lua/rustaceanvim/neotest/init.lua
> feat(neotest): basic support for `suite = true`

- lua/rustaceanvim/neotest/init.lua
- lua/rustaceanvim/neotest/trans.lua
This PR fixes calculating positions for nested test modules. 
I've removed the `dir` position as well as that was restricting neotest to a single file rather than the project directory, and was also preventing positions being updated when changing buffers.
I also had to add some naive matching logic to `is_test_file` as without the overriden `dir` position neotest will show all `.rs` files in the project directory, even if they contain no tests.
> fix(neotest): nested modules + position updates when switching buffers

- CHANGELOG.md
- lua/rustaceanvim/lsp.lua
- lua/rustaceanvim/os.lua
- lua/rustaceanvim/rust_analyzer.lua
In PR https://github.com/mrcjkb/rustaceanvim/pull/152, rustacenavim begin storing the `root_dir` with a normalized disk drive format to avoid spawning multiple rust-analyzers while navigating files.
This change caused an unintend regression on the neotest integration, as
'vim.startswith' will not match the passed in `path_files`.
https://github.com/mrcjkb/rustaceanvim/blob/4987d4159df2f80eb1deda1793ad54082d8ba454/lua/rustaceanvim/rust_analyzer.lua#L77
In summary, neotest would send the following:
```
:Neotest run file
-- -> file_path: C:\Users\me\repos\project\src\lib.rs
-- -> root_dir: c:\Users\me\projects\src\lib.rs
-- -> vim.startswith(file_path, root_dir) -- false
No tests found!
```
This commit changes the `rust_analyzer` function to ensure we use the normalized file path when …
> fix(lsp,neotest): normalize file before root_dir comparison 

- CHANGELOG.md
- lua/rustaceanvim/runnables.lua
When `cargo-nextest` is detected, it becomes the executable to trigger `testable` runnables.
Unfortunally, `nextest` does not support doc tests. This causes the doctest runnables to fail when the binary is available on the path.
This commit prevents the use of 'nextest' for 'doctest' runnables, falling back to the `cargo test --doc` executable in this case.
This way, we can do `:RustLsp testables` and run both `#[tests]` and `doctests` properly.
---
If applicable:
> fix(testables): Prevent using nextest for doctests

- CHANGELOG.md
- lua/rustaceanvim/neotest/init.lua
- lua/rustaceanvim/neotest/trans.lua
The current neotest integration reports any 'test' runnable as a valid position, except for 'doctests'.
This commit introduces logic necessary to also expose 'doctests' as part of the summary, so it can be visualized and trigger.
It tries to approach it with the minimal changes, so exported labels follows the same name convention as test runnables, without indication they are doctests on the summary window. This can be changed if necessary.
In order for neotest to consider these items part of the tree, we must also return a 'pos' with `pos.type = 'file'`, otherwhise those test items would not have a parent, and it prevents being displayed. This is done by reporting a 'file' always, but I'm not sure what is the reason behind returning only if `#namespaces > 0`.
---
If applicable:
> feat(neotest): Expose doctests on Neotest summary window

- lua/rustaceanvim/cargo.lua
- lua/rustaceanvim/os.lua
Lsp does not work in a simple cargo project when you jump into standard library multiple times by using `gd` (go to definition). Basically, rustaceanvim is not able to identify the buffer path as being inside the standard library, therefore, it launches a new instance of rust-analyzer. This happens because the path of rustup home toolchains is like `C:\path\to\rustup-home/.toolchains` while the buffer path is `c:\path\to\rustup-home\.toolchains\to\std\lib`.
Substitute all patterns `/+` with `\` and also use `os.normalize_path_on_windows` due to lowercase partition drive letter. 
I also thought of modifying the joinpath function in `compat.lua`, but it won't work with neovim 0.10.
OS: **Windows**
Neovim: **0.9.5**
Neovim config: custom LazyVim with default rustaceanvim config
> fix(lsp/windows): path normalisation preventing lsp to work after gd to std lib

- CHANGELOG.md
- doc/rustaceanvim.txt
- lua/rustaceanvim/lsp.lua
Following the discussion we had in #286, I found out how to reload settings using `workspace/didChangeConfiguration`.
Turns out the lsp server responds by a `workspace/configuration` where the server actually pulls the new configuration, since the server can cache configuration and decides whether it needs to actually pull the config.
`nvim` handles it, but we need to set the `client.settings` table to the new configuration before sending the `workspace/didChangeConfiguration` because it seems to be the one used by nvim to send the actual config.
I added this feature as a command because it made sense to me, let me know if it does not for you.
Once again, tested the changes on https://github.com/GuillaumeLagrange/neoconf-repro and it works for me.
Cheers
> feat(lsp): add command to reload lsp settings

- doc/rustaceanvim.txt
- lua/rustaceanvim/init.lua
Straightforward docs fix to correctly indicate that the hover subcommand is "actions", not "action".
> docs: fix docs for hover actions subcommand

- CHANGELOG.md
- lua/rustaceanvim/overrides.lua
> fix(lsp): escape character inserted before `}` on code action

- CHANGELOG.md
- README.md
- doc/rustaceanvim.txt
- lua/rustaceanvim/commands/debuggables.lua
- lua/rustaceanvim/commands/init.lua
- lua/rustaceanvim/init.lua
- lua/rustaceanvim/runnables.lua
> feat: `run` and `debug` commands to run targets at current position

- CHANGELOG.md
- doc/rustaceanvim.txt
- lua/rustaceanvim/commands/code_action_group.lua
- lua/rustaceanvim/config/init.lua
- lua/rustaceanvim/config/internal.lua
Adds an option to customise the group action icon like so:
```lua
vim.g.rustaceanvim = {
tools = {
code_actions = {
group_icon = " ->"
}
}
}
```
🫡
> feat(config): customisable group action icon

- CHANGELOG.md
- lua/rustaceanvim/overrides.lua
> fix(neotest): multiple `--no-run` flags added to debug command

- CHANGELOG.md
- lua/rustaceanvim/commands/diagnostic.lua
There were a couple different issues with the search for the next valid diagnostic location, which I've separated out into their own commits.
I used stylua and luacheck directly instead of through nix (because I was too lazy to set it up :see_no_evil: ) but they seemed to be satisfied with what I had. If I've missed anything just let me know. Similarly, I had six tests fail when I ran `luarocks --local test` but the same six tests fail even without my changes so hopefully that's fine.
Thanks for all your work on this project by the way! I only recently started in rust and having the inline diagnostics show up as I work has been a huge time saver while I'm learning the ropes : )
To reproduce the issue, turn on the `clippy::shadow_unrelated` lint and try to cycle between the three lints in …
> fix(lsp): renderDiagnostics and explainError skipping valid diagnostics

- lua/rustaceanvim/server_status.lua
Hi! Thanks for such a great plugin.
Neovim has changed the parameters of the `is_enabled` now it takes a filter similar to a change they did for enabling them a few weeks ago! here's a quick fix, if it suits you!
> fix(lsp): update `inlay_hints.is_enabled` to new nightly format

- CHANGELOG.md
- lua/rustaceanvim/commands/diagnostic.lua
- lua/rustaceanvim/config/check.lua
- lua/rustaceanvim/config/internal.lua
when opening splits from a floating window with the "Open in split" option, this will set the split to open vertically.
configure with:
```lua
vim.g.rustaceanvim = {
tools = {
float_win_config = {
open_split = 'vertical',
},
},
}
```
> feat(ui): add `open_split_vertical` option for splits opened

- lua/rustaceanvim/executors/termopen.lua
Use ":" to enter command mode, not silent by default.
In addition to this, using `<Cmd>...<CR>` has many advantages:
https://neovim.io/doc/user/map.html#%3CCmd%3E
> fix(termopen): "<Esc>" to close buffer not silent

- troubleshooting/minimal.lua
Not everyone has SSH clone method configured (correctly) and HTTPS is supposed to work for anyone.
> chore(troubleshooting): Use HTTPS clone for lazy

- lua/rustaceanvim/config/server.lua
The correct config key for a rust-analyzer check command table is `check`. `checkOnSave` is a boolean.
<https://rust-analyzer.github.io/manual.html#configuration>
There are some hints in the manual that `checkOnSave` as a table is aliased to `check` but even if it is the correct key is `check`.
This prevents incorrect config conflicts downstream.
> fix(enable_clippy): use correct rust-analyzer config key

- CHANGELOG.md
- ftplugin/rust.lua
> perf(lsp): defer attaching client to `BufEnter`

- lua/rustaceanvim/config/server.lua
- spec/56_spec.lua
The allFeatures  setting is disabled by RA, and deprecated for two year.
ref: https://github.com/rust-lang/rust-analyzer/issues/17371#issuecomment-2169149906
> fix: don't set deprecated `allFeatures` setting by default

- CHANGELOG.md
- lua/rustaceanvim/dap.lua
The PR fixes two small issues in the `add_dynamic_library_paths` method:
1. Dynamic linking didn't work on `macOS` due to a typo in the `DYLD_LIBRARY_PATH` constant.
2. Dynamic linking didn't work while using `nightly toolchain` (at least on `macOS`).
The problem was found when I tried to use `rustaceanvim` with `Cargo.toml` settings recommended for `bevy engine`: (https://bevyengine.org/learn/quick-start/getting-started/setup/).
**FYI: Unfortunately I can't test that on systems.**
> fix(dap): dynamic library path setup fix

- README.md
A bit of a shameless plug, but when exploring this plugin I noticed that the README says that core doesn't support autocompletion, but as of https://github.com/neovim/neovim/pull/27339 it does :)
> docs: update current support for built-in completion

- CHANGELOG.md
- lua/rustaceanvim/config/internal.lua
The `background` one is nice, but it doesn't have a way to show log output.
> chore(testables): default to `termopen` test executor if not using `neotest`

- CHANGELOG.md
- README.md
- lua/rustaceanvim/commands/diagnostic.lua
- lua/rustaceanvim/commands/init.lua
- lua/rustaceanvim/init.lua
feat(lsp): explainError and renderDiagnostic command now have optional argument {cycle?|current?}. It default to cycle which is current behavior, current option makes it search for diagnostic only in the current cursor line
> feat(lsp): Arguments to explainError/renderDiagnostic from current line

- CHANGELOG.md
- lua/rustaceanvim/commands/debuggables.lua
- lua/rustaceanvim/dap.lua
- lua/rustaceanvim/runnables.lua
> fix(dap): account for removed `cargoExtraArgs`

- CHANGELOG.md
- doc/rustaceanvim.txt
- lua/rustaceanvim/cargo.lua
- lua/rustaceanvim/commands/rustc_unpretty.lua
- lua/rustaceanvim/config/check.lua
- lua/rustaceanvim/config/init.lua
- lua/rustaceanvim/config/internal.lua
> feat: auto-detect the rustc edition

- lua/rustaceanvim/commands/fly_check.lua
I tested this and it fixes https://github.com/mrcjkb/rustaceanvim/issues/465, the clear/cancel subcommands for flyCheck command work.
> fix(diagnostic): pass correct flycheck arg for clear/cancel

- lua/rustaceanvim/commands/code_action_group.lua
Using `#M.state.actions.group` stops (and returns 0) when a nil is encountered.
Use `vim.tbl_count()` instead which will return an integer
> fix(ui): `nil` safety in codeAction Group

- lua/rustaceanvim/lsp.lua
This is a prerequisite to using `workspace_discoverConfig` at all, since if it isn't present in the initialization RPC, then rust-analyzer just discovers a cargo project and never looks at workspace_discoverConfig ever again. The discoverConfig stuff is pretty unstable but this at least gets things going.
Note that VSCode does it this way as well. I think at this point we may be sending too many didChangeConfiguration RPCs, but at least stuff works!
Example config -- using `rust-project` from the [buck2](https://github.com/facebook/buck2) project
(Put this in a `rust-analyzer.json` file for rustaceanvim to find. The `rust-analyzer.toml` support in R-A itself is still incapable of reading the file at startup... :/)
```json
{
"rust-analyzer.workspace.discoverConfig": {
"command": [ …
```
> fix(lsp): copy settings to init_options when starting the server to match VSCode

- lua/rustaceanvim/config/internal.lua
`lldb-dap` has supported integrated terminal and we can use this feature by default which is consistent with the behavior of `codelldb`.
OS: macOS 14.6.1
Arch: arm64
LLVM: 18.1.8
> feat(dap): use integrated terminal for lldb-dap by default

- CHANGELOG.md
- lua/rustaceanvim/server_status.lua
> feat(lsp): notify if rust-analyzer status is not healthy

- CHANGELOG.md
- lua/rustaceanvim/config/internal.lua
- lua/rustaceanvim/server_status.lua
When the rust-analyzer server emits errors or warnings, display the additional message. Don't de-duplicate messages otherwise we loose the feedback on whether we have solved the issue.
> feat(lsp): more information on LSP errors

- lua/rustaceanvim/dap.lua
> fix: remove luajit requirement

- doc/rustaceanvim.txt
- lua/rustaceanvim/config/init.lua
- lua/rustaceanvim/config/internal.lua
- lua/rustaceanvim/server_status.lua
> feat(lsp): only notify on server status error by default

- lua/rustaceanvim/commands/move_item.lua
Port https://github.com/simrat39/rust-tools.nvim/pull/386
```rust
pub struct Allergies(u32);
macro_rules! enum_iter {
($name: ident { $($variant: ident),* } ) => {
#[derive(Debug, PartialEq, Eq, Clone)]
pub enum $name {
$( $variant, )*
}
impl $name {
fn variants() -> Vec<$name> {
vec![$( $name::$variant, )*]
}
}
};
}
enum_iter!(Allergen {
Eggs,
Peanuts,
Shellfish,
Strawberries,
Tomatoes,
Chocolate,
Pollen,
Cats
});
impl Allergies {
pub fn new(score: u32) -> Self {
Allergies(score)
}
pub fn is_allergic_to(&self, allergen: &Allergen) -> bool {
(self.0 & 1_u32 << allergen.clone() as u32) != 0
}
pub fn allergies(&self) -> Vec<Allergen> {
Allergen::variants()
.iter()
.filter_map(|allergen| self.is_allergic_to(allergen).then_some(allergen.clone()))
.collect()
}
}
```
> feat(lsp): preserve cursor position for move_item command

- doc/mason.txt
Hey, thanks for the great plugin !
Long story short, I've noticed that the executable name for the latest rust-analyzer shipped by Mason differs between OSes, but we can retrieve that from the metadata provided by Mason.
I've modified the docs in kind, but would be happy to contribute to a more automated discovery mechanism if desirable.
Hope this helps 🦀
> docs(mason): more generic config snippet

- lua/rustaceanvim/lsp/init.lua
- lua/rustaceanvim/rust_analyzer.lua
- lua/rustaceanvim/rustc.lua
> perf: optimize target_arch switching

- README.md
The example hotkey-configuration I tried to paste had a syntax error because of a missing ')'.
> docs(readme): Added ')' to avoid lua syntax error

- lua/rustaceanvim/lsp/init.lua
> feat(lsp): allow overriding server command via `rust-analzyer.server.path` setting

- lua/rustaceanvim/compat.lua
Add missing return to avoid calling the nil show_document below.
> chore(fixup): compatibility with nvim release

- doc/rustaceanvim.txt
- lua/rustaceanvim/config/init.lua
- lua/rustaceanvim/config/internal.lua
- lua/rustaceanvim/server_status.lua
Fixes #582 .
This PR allows us to safely define and execute buffer-local commands in the `on_initialized` function by querying the buffers used by the LSP client identified by the newly added `client_id` parameter.
This is backward compatible, since the `client_id` was added after the existing parameter, not before.
I did the following tests.
```lua
--[[
1. Open two Rust projects in a single Neovim instance.
cd project
nvim -o src/main.rs ~/another_rust_project/src/main.rs
2. Wait for the two LSP clients to finish indexing.
3. Run `:messages`.
I got the following output. It's working as expected.
{
client_id = 1,
status = {
health = "ok",
quiescent = true
}
}
{
client_id = 2,
status = {
health = "ok",
quiescent = true
}
}
]]
local function on_initialized(status, client_id)
vim.print({ …
```
> feat(lsp): pass client_id to on_initialized (#582)

- doc/rustaceanvim.txt
- lua/rustaceanvim/config/init.lua
- lua/rustaceanvim/config/internal.lua
- lua/rustaceanvim/server_status.lua
> feat(lsp): pass `client_id` to `on_initialized`

- lua/rustaceanvim/lsp/init.lua
This PR fixes  #588 by making the target architecture switching command for `RustAnalyzer` show up in neovim's command auto completion.
> fix: expose `target` scommand in `:RustAnalyzer` command completion

- lua/rustaceanvim/lsp/init.lua
This PR addresses three issues that would prevent a user from successfully running `:RustAnalyzer target`. It is pretty much a follow up to https://github.com/mrcjkb/rustaceanvim/pull/589 and https://github.com/mrcjkb/rustaceanvim/pull/548.
Each commit fixes one issue, and I will explain them in order:
`:RustAnalyzer target` would call `set_target_arch` by passing the target triple as the `bufnr` argument. Seems to be a regression introduced in https://github.com/mrcjkb/rustaceanvim/pull/548 AFAICT.
Inside `set_target_arch`, we would try to update a nested map (`rust-analyzer`)  without first checking if each subkey was present. Specifically, `client.settings['rust-analyzer'].cargo` was `nil`, leading to the following statement failing catastrophically: …
> fix: various `:RustAnalyzer target` regressions

- lua/rustaceanvim/neotest/init.lua
> fix(neotest): prevent coloured output when using cargo-nextest

- lua/rustaceanvim/commands/diagnostic.lua
Update: updated the description according mrcjkb's newest requirements.
As the title said, running the commands twice will focus the pop up instead of closing the hover and opening it again.
According to neovim's documentation for
vim.lsp.util.open_floating_preview:
> If `true`, and if {focusable} is also `true`, focus an existing floating
> window with the same {focus_id}
> (default: `true`)
Removing the focus=false, and removing call to close_hover enable users
to enter the hover.
I removed the your parameter focus=false, so that nvim will use the default parameter focus=true, then when calling the open_floating_preview twice, it would focus an existing floating window with the same {focus_id}. 
If you have any other questions or understanding the code, please run `:h …
> feat(diagnostics): focus preview window when invoking commands again with `current` argument

- lua/rustaceanvim/config/server.lua
Closes #615 
I'm fairly new to this, so please let me know if extending both capabilities on top of each other when both are available is really a good idea :)
> feat(lsp): support `blink.cmp`

- lua/rustaceanvim/health.lua
- lua/rustaceanvim/overrides.lua
Fixes https://github.com/mrcjkb/rustaceanvim/issues/618.
I have tested this manually:
1. Uninstalled the `cargo-nextest`
2. Installed 0.9.80 (which does not support the flag)
3. Installed the correct version
I have tested the tests are now not executed if not needed (for example when running `test_function_1`:
```
Finished `test` profile [unoptimized + debuginfo] target(s) in 0.01s
────────────
Nextest run ID a08a7486-cd35-4d6d-b0ce-4cde971c1b3c with nextest profile: default
Starting 1 test across 1 binary (1 test skipped)
PASS [   0.017s] rust-test::bin/rust-test test::test_function_1
────────────
Summary [   0.019s] 1 test run: 1 passed, 1 skipped
```
> fix(neotest): prevent running multiple tests when running a single test with cargo-nextest

- README.md
- doc/rustaceanvim.txt
- doc/tags
- lua/rustaceanvim/config/init.lua
- lua/rustaceanvim/config/internal.lua
- lua/rustaceanvim/lsp/init.lua
> feat(lsp): auto-connect to ra-multiplex if running

- doc/rustaceanvim.txt
- lua/rustaceanvim/config/init.lua
- lua/rustaceanvim/lsp/init.lua
> feat(lsp): preliminary support for `vim.lsp.config`

- lua/rustaceanvim/config/json.lua
- lua/rustaceanvim/config/server.lua
> fix(health): .vscode settings reported as loaded if .vscode/ is empty

- lua/rustaceanvim/config/internal.lua
> fix(lsp/windows): unable to find rust-analyzer executable binary

- lua/rustaceanvim/health.lua
We should disable the dap health check when the dap feature is disabled.
> feat(health): disable dap health check when dap is disabled

- lua/rustaceanvim/executors/termopen.lua
Fixes #674 
Once again, Neovim has deprecated a command, proposing an alternative that is not available in non-nightly :disappointed:.
> revert(termopen): replace termopen with jobstart

- lua/rustaceanvim/config/internal.lua
Addresses
https://github.com/mrcjkb/rustaceanvim/issues/678
> fix(config/dap): use absolute path to debug adapter if available

- lua/rustaceanvim/config/internal.lua
Recently, @williamboman announced version 2.0 of Mason. This patch accommodates these changes while continuing to support the old version.
> feat: add mason v2.x support

- lua/rustaceanvim/commands/fly_check.lua
Hi, I encountered a problem and try to solve it.
When I manually trigger a flyCheck via `:RustLsp flyCheck`, the rust analyzer does not perform the corresponding flyCheck.
The minimal configuration of rust analyzer as follows.
```lua
["rust-analyzer"] = {
check = {
command = "check",
workspace = false,
},
}
```
Looked through the code of the rust analyzer and found that the serialization of the `flycheck_params` is problematic. The related code see [here](https://github.com/rust-lang/rust-analyzer/blob/62e7d9f0fc2a3499be2ed819c572da875e564ee0/crates/rust-analyzer/src/lsp/ext.rs#L373-L377).
And this PR fixes the serialization problem of `flycheck_params`.
> fix(lsp): FlyCheck request params

- lua/rustaceanvim/compat.lua
I assume that this issue was silent, because we used `jump_to_location` method instead. Since now this method is deprecated we can see that `show_document` is never called. The correct location of `show_document` method is in [util](https://neovim.io/doc/user/lsp.html#vim.lsp.util.show_document())
closes #710
> fix: deprecation warning on go to definition hover action (nvim 0.11)

- README.md
- lua/rustaceanvim/commands/syntax_tree.lua
Fixes #709.
rust-analyzer removed `rust-analyzer/syntaxTree` and added `rust-analyzer/viewSyntaxTree` in https://github.com/rust-lang/rust-analyzer/pull/18813.
> [!NOTE]
>
> This PR only unbreaks the command. It does not implement any of the new syntax tree viewer features.
> Since I don't use this myself, I don't have the capacity to implement them, but PRs are welcome.
> fix: broken syntaxTree command

- lua/rustaceanvim/commands/hover_range.lua
When I remove `vim.lsp.handlers[vim.lsp.protocol.Methods.textDocument_hover] = vim.lsp.with(vim.lsp.handlers.hover, { border = "single" })` in neovim 0.11, hover range missing border.
I tried `vim.opt.winborder = "single"` but it was too noise.
I noticed that when I press `KK`(the K call hover range) continuously it stays in visual mod, and I need press `<esc>q` for exit float window so I let it automatically switch to nomal mod.
> fix(hover_range): missing border

- README.md
- doc/rustaceanvim.txt
This PR fixes some outdated links to the rust-analyzer configuration documentation.
> docs: update rust-analyzer config links

- lua/rustaceanvim/cargo.lua
> fix: regression in root directory detection

- lua/rustaceanvim/commands/code_action_group.lua
This fixes #744, which was thought to be caused by "copilot.vim", but actually happens anytime `rust-analyzer` does not have `id: 1`. We thought that this case was already handled (see: https://github.com/mrcjkb/rustaceanvim/issues/744#issuecomment-2848679366), but it turns out that it wasn't.
According to the lua manual:
> ipairs (t)
> 
> Returns three values (an iterator function, the table t, and 0) so that the construction
> 
>      for i,v in ipairs(t) do body end
> 
> will iterate over the key–value pairs (1,t[1]), (2,t[2]), ..., __up to the first absent index__. (emphasis mine).
What happens is that the `result` table returned by 
```lua
vim.lsp.buf_request_all(0, 'textDocument/codeAction', params, function(results, ctx) 
-- handle `result` table.
end)
```
is sparse with respect to …
> fix(lsp): codeActions not found if multiple clients are active

- lua/rustaceanvim/commands/code_action_group.lua
Should fix an old bug that has been present since the inception of the code action group feature in rust-tools.nvim.
Closes #753.
> fix(lsp/codeAction): missing `execute_command` function

- README.md
- doc/rustaceanvim.txt
- lua/rustaceanvim/commands/diagnostic.lua
- lua/rustaceanvim/commands/init.lua
- lua/rustaceanvim/init.lua
This adds a `cycle_prev` option to `explainError` and `renderDiagnostic` like `vim.diagnostic.goto_prev`.
> feat(lsp): add `cycle_prev` arg to `explainError` and `renderDiagnostic` commands

- doc/rustaceanvim.txt
- lua/rustaceanvim/config/init.lua
- lua/rustaceanvim/executors/background.lua
- lua/rustaceanvim/executors/quickfix.lua
- lua/rustaceanvim/executors/termopen.lua
- lua/rustaceanvim/executors/toggleterm.lua
- lua/rustaceanvim/executors/vimux.lua
- lua/rustaceanvim/neotest/init.lua
- lua/rustaceanvim/runnables.lua
Closes #770.
@mrcjkb Thanks for marking #770 as a good first issue! As a novice in Neovim plugin development, I decided to give it a shot. Please feel free to provide suggestions on how I may improve this patch, and many thanks in advance 🙏 
I cannot say for all backends, but at least the `nextest` backend is known to work with this patch according to my manual testing.
> feat(lsp/runnables): support `runnable.args.environment`

- doc/rustaceanvim.txt
- lua/rustaceanvim/commands/external_docs.lua
- lua/rustaceanvim/config/server.lua
I opened #805 yesterday. Turns out, it's really not rocket science to implement.
I am worried about HTML URIs potentially being handled by a text editor, though.
Also, we're implicitly relying on outdated documentation for local types, as there's nothing that rebuilds it on save. It is still better than a 404 page, I think.
And I sure hope all 4 opening strategies can handle `file://` identifiers.
I couldn't properly run `luarocks` tests.
> feat(lsp): `experimental/localDocs` support
