mrcjkb/rustaceanvim

CHANGELOG.md, lua/rustaceanvim/dap.lua
=> fix(dap): make sourceMap a list of tuples, not a map

CHANGELOG.md, README.md, lua/rustaceanvim/commands/fly_check.lua
=> fix(flyCheck): correct typo in LSP client request

CHANGELOG.md, README.md, lua/rustaceanvim/commands/init.lua, lua/rustaceanvim/commands/view_ir.lua
=> feat: `RustLsp view [mir|hir]` command

CHANGELOG.md, README.md, doc/rustaceanvim.txt, lua/rustaceanvim/commands/debuggables.lua, lua/rustaceanvim/commands/init.lua, lua/rustaceanvim/init.lua, lua/rustaceanvim/runnables.lua
=> feat!(lsp,dap): allow overriding runnable/debuggable executable args

CHANGELOG.md, README.md, doc/rustaceanvim.txt, lua/rustaceanvim/cached_commands.lua, lua/rustaceanvim/commands/init.lua, lua/rustaceanvim/config/init.lua, lua/rustaceanvim/config/internal.lua, lua/rustaceanvim/executors/background.lua, lua/rustaceanvim/executors/init.lua, lua/rustaceanvim/executors/quickfix.lua, lua/rustaceanvim/executors/termopen.lua, lua/rustaceanvim/executors/toggleterm.lua, lua/rustaceanvim/executors/vimux.lua, lua/rustaceanvim/init.lua, lua/rustaceanvim/runnables.lua, spec/parse_test_result_spec.lua
=> feat(lsp): `RustLsp testables` command + failed test diagnostics

.neoconf.json, CHANGELOG.md, README.md, doc/rustaceanvim.txt, flake.nix, lua/rustaceanvim/cached_commands.lua, lua/rustaceanvim/cargo.lua, lua/rustaceanvim/commands/debuggables.lua, lua/rustaceanvim/compat.lua, lua/rustaceanvim/config/check.lua, lua/rustaceanvim/config/init.lua, lua/rustaceanvim/config/internal.lua, lua/rustaceanvim/dap.lua, lua/rustaceanvim/executors/background.lua, lua/rustaceanvim/executors/init.lua, lua/rustaceanvim/executors/meta.lua, lua/rustaceanvim/executors/neotest.lua, lua/rustaceanvim/health.lua, lua/rustaceanvim/lsp.lua, lua/rustaceanvim/neotest/init.lua, lua/rustaceanvim/neotest/trans.lua, lua/rustaceanvim/overrides.lua, lua/rustaceanvim/runnables.lua, lua/rustaceanvim/test.lua, nix/docgen.nix, spec/test_spec.lua
=> feat: neotest adapter

CHANGELOG.md, README.md, doc/rustaceanvim.txt, lua/rustaceanvim/commands/init.lua, lua/rustaceanvim/commands/workspace_symbol.lua, lua/rustaceanvim/compat.lua, lua/rustaceanvim/init.lua
=> feat(lsp): filtered workspace symbol searches

.github/workflows/release.yml, CHANGELOG.md, lua/rustaceanvim/compat.lua, lua/rustaceanvim/executors/termopen.lua, lua/rustaceanvim/executors/vimux.lua, lua/rustaceanvim/shell.lua
=> fix(runnables): `cd` into directory with spaces not working

CHANGELOG.md, lua/rustaceanvim/commands/rustc_unpretty.lua
To adjust the command parameters.
=> feat(rustc): do not require a main function + support 2024 edition

CHANGELOG.md, lua/rustaceanvim/config/server.lua
=> fix(lsp): `checkOnSave = false` not respected if clippy is installed

CHANGELOG.md, lua/rustaceanvim/commands/rebuild_proc_macros.lua, lua/rustaceanvim/commands/workspace_refresh.lua, lua/rustaceanvim/commands/workspace_symbol.lua, lua/rustaceanvim/rust_analyzer.lua
=> fix(lsp): allow to run some RustLsp commands from non-rust buffers

CHANGELOG.md, lua/rustaceanvim/commands/code_action_group.lua, lua/rustaceanvim/hover_actions.lua
=> fix(ui): explicitly disable signcolumn for floating windows

CHANGELOG.md, lua/rustaceanvim/cached_commands.lua, lua/rustaceanvim/commands/init.lua
=> feat(lsp): support falling back to ui select for `testables/runnables`

CHANGELOG.md, lua/rustaceanvim/commands/diagnostic.lua
=> fix(ui): buggy concealing of elements in rendered diagnostics

CHANGELOG.md, lua/rustaceanvim/config/check.lua
=> fix(config): don't validate types defined in external APIs

CHANGELOG.md, lua/rustaceanvim/dap.lua, lua/rustaceanvim/lsp.lua
=> fix(dap): don't error if getting source/library info fails

CHANGELOG.md, lua/rustaceanvim/health.lua
=> feat(health): detect rust-analyzer wrapper without rust-analyzer

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, lua/rustaceanvim/neotest/init.lua, lua/rustaceanvim/neotest/trans.lua
=> fix(neotest): correctly mark passed and skipped tests in file/module runs

CHANGELOG.md, README.md, doc/rustaceanvim.txt, lua/rustaceanvim/commands/init.lua, lua/rustaceanvim/init.lua
=> feat: `:RustLsp openDocs` command

CHANGELOG.md, doc/rustaceanvim.txt, lua/rustaceanvim/commands/debuggables.lua, lua/rustaceanvim/config/check.lua, lua/rustaceanvim/config/init.lua, lua/rustaceanvim/config/internal.lua, lua/rustaceanvim/dap.lua, lua/rustaceanvim/health.lua, lua/rustaceanvim/runnables.lua
=> feat: `tools.cargo_override` option

CHANGELOG.md, lua/rustaceanvim/commands/code_action_group.lua
=> fix(ui): `float_win_config.border` not applied to code action group

CHANGELOG.md, flake.lock, lua/rustaceanvim/server_status.lua
=> chore(lsp): update neovim nightly API call

CHANGELOG.md, lua/rustaceanvim/cargo.lua
=> fix(lsp): error when opening a rust file that does not exist

CHANGELOG.md, lua/rustaceanvim/lsp.lua
=> feat(lsp): enable server-side file watching if client-side disabled

lua/rustaceanvim/commands/code_action_group.lua, lua/rustaceanvim/compat.lua, lua/rustaceanvim/health.lua
This fixes deprecated warnings in nvim nightly.
=> fix(lsp): update deprecated API calls

lua/rustaceanvim/config/json.lua, lua/rustaceanvim/health.lua, spec/json_spec.lua
=> feat(config): health check reports for .vscode/settings.json

lua/rustaceanvim/shell.lua
=> fix: work around bug in Nushell on Windows

doc/rustaceanvim.txt, doc/tags, lua/rustaceanvim/commands/code_action_group.lua, lua/rustaceanvim/config/check.lua, lua/rustaceanvim/config/init.lua, lua/rustaceanvim/config/internal.lua
=> feat(lsp/codeAction): make float window keymaps configurable

lua/rustaceanvim/health.lua
Corrected method names in external_deps section
=> fix(health): correct method names in external_deps section

lua/rustaceanvim/config/internal.lua
=> fix(dap): set `sourceLanguages` when using `codelldb`

lua/rustaceanvim/lsp/init.lua
=> fix(lsp): client attach issue when loading vim session script

lua/rustaceanvim/commands/code_action_group.lua
=> fix(ui): use Nvim 0.11 codeaction table structure

lua/rustaceanvim/commands/code_action_group.lua
Continuation of #739. Fixes #738.
=> fix(ui): use Nvim 0.11 codeaction table structure (continued)

doc/mason.txt
=> docs(vimdoc): update mason-lspconfig conflict note

lua/rustaceanvim/commands/diagnostic.lua
This fixes an issue where `renderDiagnostics` opens a seemingly empty float window. The content is there but comes after the visible lines.
=> fix(ui/renderDiagnostics): seemingly empty float window

lua/rustaceanvim/commands/code_action_group.lua, lua/rustaceanvim/commands/init.lua
I've followed ssr, it seems working for me.
Closes: #800
=> feat(lsp): visual mode support for code actions

doc/rustaceanvim.txt, lua/rustaceanvim/config/init.lua, lua/rustaceanvim/config/server.lua
=> fix(help): remove outdated documentation

lua/rustaceanvim/cache.lua, lua/rustaceanvim/executors/background.lua, lua/rustaceanvim/neotest/init.lua, lua/rustaceanvim/neotest/parser.lua, lua/rustaceanvim/overrides.lua, lua/rustaceanvim/test.lua, nextest.toml, spec/neotest_spec.lua, spec/test_spec.lua
also fixes general test status checks
related issues: 
- https://github.com/mrcjkb/rustaceanvim/issues/554
- https://github.com/mrcjkb/rustaceanvim/issues/462
=> feat(tests): support nextest junit + enable colour output

lua/rustaceanvim/neotest/init.lua, lua/rustaceanvim/test.lua, spec/test_spec.lua
=> fix(test): various test/neotest fixes and improvements
